package exceptions;

/**
 * Created by Yu on 2017/12/2.
 */
public enum Error {
    VARIABLE_NOT_FOUND,VARIABLE_EXISTS ,NOT_INTEGER_TYPE, UNEXPECTED_STATMENT, EXPRESSION_ERROR, ARRAY_ASSIGN_ERROR,INDEX_OUT_OF_BOUND
, TOKEN_ERROR, UNKNOWN_ERROR, VARIABLE_ASSIGN_ERROR, FUNCTION_DECLARE_ERROR, FUNCTION_NOT_FOUND,REDUNDENT_DECLARATION
}
